$(document).ready(function(){
    $('#modal').hide();
    $('.content1').hide();
    $('.content2').hide();
    $('.content3').hide();
    $('.content4').hide();
    $('.part-2').addClass('an');
    $('.part-3').hide();
    $('#btn1').click(function(){
        $('.part-1').addClass('an');
        $('.part-2').removeClass('an');
    });
    $('#btn2').click(function(){
        $('.part-2').addClass('an');
        $('.part-3').show();
    });
    $('.btn3').hover(function(){
        $('.btn3').addClass('an');
        $('.btn5').addClass('an');
        $('.btn6').addClass('an');
        $('.btn4').removeClass('an');
        
    });
    $('.btn4').hover(function(){
        $('.btn4').addClass('an');
        $('.btn6').addClass('an');
        $('.btn3').addClass('an');
        $('.btn5').removeClass('an');
    });
    $('.btn5').hover(function(){
        $('.btn3').addClass('an');
        $('.btn4').addClass('an');
        $('.btn5').addClass('an');
        $('.btn6').removeClass('an');
        $('#modal').show();
        $('.content1').show();
        $('.content2').show();
        $('.content3').show();
        $('.content4').show();
    });
    $('.btn6').hover(function(){
        $('.btn4').addClass('an');
        $('.btn5').addClass('an');
        $('.btn6').addClass('an');
        $('.btn3').removeClass('an');
    });
    $('.content1').click(function(){
        $('#modal').hide();
        $('.content1').hide();
        $('.content2').hide();
        $('.content3').hide();
        $('.content4').hide();
    });
    $('.content2').click(function(){
        $('#modal').hide();
        $('.content1').hide();
        $('.content2').hide();
        $('.content3').hide();
        $('.content4').hide();
    });
    $('.content3').click(function(){
        $('#modal').hide();
        $('.content1').hide();
        $('.content2').hide();
        $('.content3').hide();
        $('.content4').hide();
    });
    $('.content4').click(function(){
        $('#modal').hide();
        $('.content1').hide();
        $('.content2').hide();
        $('.content3').hide();
        $('.content4').hide();
    });
});
